name 'mywebcookbook'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures mywebcookbook'
long_description 'Installs/Configures mywebcookbook'
version '0.1.0'
